# Generated by Django 6.0.5 on 2026-05-07 03:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_banner_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='banner',
            name='image',
        ),
    ]
