# Generated by Django 6.0.5 on 2026-05-07 04:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0003_remove_banner_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='banner',
            old_name='cta_text',
            new_name='button_text',
        ),
        migrations.RemoveField(
            model_name='banner',
            name='discount',
        ),
        migrations.RemoveField(
            model_name='banner',
            name='sub_text',
        ),
        migrations.RemoveField(
            model_name='banner',
            name='tagline',
        ),
        migrations.AddField(
            model_name='banner',
            name='button_position',
            field=models.CharField(choices=[('left', 'Left'), ('right', 'Right')], default='left', max_length=10),
        ),
        migrations.AddField(
            model_name='banner',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='banners/'),
        ),
    ]
